"use strict";(self.webpackChunkdetekt_website=self.webpackChunkdetekt_website||[]).push([[2356],{3905:function(e,n,t){t.d(n,{Zo:function(){return s},kt:function(){return m}});var o=t(7294);function a(e,n,t){return n in e?Object.defineProperty(e,n,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[n]=t,e}function i(e,n){var t=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);n&&(o=o.filter((function(n){return Object.getOwnPropertyDescriptor(e,n).enumerable}))),t.push.apply(t,o)}return t}function l(e){for(var n=1;n<arguments.length;n++){var t=null!=arguments[n]?arguments[n]:{};n%2?i(Object(t),!0).forEach((function(n){a(e,n,t[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):i(Object(t)).forEach((function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(t,n))}))}return e}function r(e,n){if(null==e)return{};var t,o,a=function(e,n){if(null==e)return{};var t,o,a={},i=Object.keys(e);for(o=0;o<i.length;o++)t=i[o],n.indexOf(t)>=0||(a[t]=e[t]);return a}(e,n);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(e);for(o=0;o<i.length;o++)t=i[o],n.indexOf(t)>=0||Object.prototype.propertyIsEnumerable.call(e,t)&&(a[t]=e[t])}return a}var p=o.createContext({}),c=function(e){var n=o.useContext(p),t=n;return e&&(t="function"==typeof e?e(n):l(l({},n),e)),t},s=function(e){var n=c(e.components);return o.createElement(p.Provider,{value:n},e.children)},d={inlineCode:"code",wrapper:function(e){var n=e.children;return o.createElement(o.Fragment,{},n)}},u=o.forwardRef((function(e,n){var t=e.components,a=e.mdxType,i=e.originalType,p=e.parentName,s=r(e,["components","mdxType","originalType","parentName"]),u=c(t),m=a,h=u["".concat(p,".").concat(m)]||u[m]||d[m]||i;return t?o.createElement(h,l(l({ref:n},s),{},{components:t})):o.createElement(h,l({ref:n},s))}));function m(e,n){var t=arguments,a=n&&n.mdxType;if("string"==typeof e||a){var i=t.length,l=new Array(i);l[0]=u;var r={};for(var p in n)hasOwnProperty.call(n,p)&&(r[p]=n[p]);r.originalType=e,r.mdxType="string"==typeof e?e:a,l[1]=r;for(var c=2;c<i;c++)l[c]=t[c];return o.createElement.apply(null,l)}return o.createElement.apply(null,t)}u.displayName="MDXCreateElement"},8695:function(e,n,t){t.r(n),t.d(n,{assets:function(){return s},contentTitle:function(){return p},default:function(){return m},frontMatter:function(){return r},metadata:function(){return c},toc:function(){return d}});var o=t(3117),a=t(102),i=(t(7294),t(3905)),l=["components"],r={title:"Exceptions Rule Set",sidebar:"home_sidebar",keywords:["rules","exceptions"],permalink:"exceptions.html",toc:!0,folder:"documentation"},p=void 0,c={unversionedId:"rules/exceptions",id:"rules/exceptions",title:"Exceptions Rule Set",description:"Rules in this rule set report issues related to how code throws and handles Exceptions.",source:"@site/docs/rules/exceptions.md",sourceDirName:"rules",slug:"/rules/exceptions",permalink:"/docs/rules/exceptions",draft:!1,editUrl:"https://github.com/detekt/detekt/edit/main/website/docs/rules/exceptions.md",tags:[],version:"current",frontMatter:{title:"Exceptions Rule Set",sidebar:"home_sidebar",keywords:["rules","exceptions"],permalink:"exceptions.html",toc:!0,folder:"documentation"},sidebar:"defaultSidebar",previous:{title:"Empty-blocks Rule Set",permalink:"/docs/rules/empty-blocks"},next:{title:"Formatting Rule Set",permalink:"/docs/rules/formatting"}},s={},d=[{value:"ExceptionRaisedInUnexpectedLocation",id:"exceptionraisedinunexpectedlocation",level:3},{value:"Configuration options:",id:"configuration-options",level:4},{value:"Noncompliant Code:",id:"noncompliant-code",level:4},{value:"InstanceOfCheckForException",id:"instanceofcheckforexception",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-1",level:4},{value:"Compliant Code:",id:"compliant-code",level:4},{value:"NotImplementedDeclaration",id:"notimplementeddeclaration",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-2",level:4},{value:"ObjectExtendsThrowable",id:"objectextendsthrowable",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-3",level:4},{value:"Compliant Code:",id:"compliant-code-1",level:4},{value:"PrintStackTrace",id:"printstacktrace",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-4",level:4},{value:"Compliant Code:",id:"compliant-code-2",level:4},{value:"RethrowCaughtException",id:"rethrowcaughtexception",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-5",level:4},{value:"Compliant Code:",id:"compliant-code-3",level:4},{value:"ReturnFromFinally",id:"returnfromfinally",level:3},{value:"Configuration options:",id:"configuration-options-1",level:4},{value:"Noncompliant Code:",id:"noncompliant-code-6",level:4},{value:"SwallowedException",id:"swallowedexception",level:3},{value:"Configuration options:",id:"configuration-options-2",level:4},{value:"Noncompliant Code:",id:"noncompliant-code-7",level:4},{value:"Compliant Code:",id:"compliant-code-4",level:4},{value:"ThrowingExceptionFromFinally",id:"throwingexceptionfromfinally",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-8",level:4},{value:"ThrowingExceptionInMain",id:"throwingexceptioninmain",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-9",level:4},{value:"ThrowingExceptionsWithoutMessageOrCause",id:"throwingexceptionswithoutmessageorcause",level:3},{value:"Configuration options:",id:"configuration-options-3",level:4},{value:"Noncompliant Code:",id:"noncompliant-code-10",level:4},{value:"Compliant Code:",id:"compliant-code-5",level:4},{value:"ThrowingNewInstanceOfSameException",id:"throwingnewinstanceofsameexception",level:3},{value:"Noncompliant Code:",id:"noncompliant-code-11",level:4},{value:"Compliant Code:",id:"compliant-code-6",level:4},{value:"TooGenericExceptionCaught",id:"toogenericexceptioncaught",level:3},{value:"Configuration options:",id:"configuration-options-4",level:4},{value:"Noncompliant Code:",id:"noncompliant-code-12",level:4},{value:"Compliant Code:",id:"compliant-code-7",level:4},{value:"TooGenericExceptionThrown",id:"toogenericexceptionthrown",level:3},{value:"Configuration options:",id:"configuration-options-5",level:4},{value:"Noncompliant Code:",id:"noncompliant-code-13",level:4},{value:"Compliant Code:",id:"compliant-code-8",level:4}],u={toc:d};function m(e){var n=e.components,t=(0,a.Z)(e,l);return(0,i.kt)("wrapper",(0,o.Z)({},u,t,{components:n,mdxType:"MDXLayout"}),(0,i.kt)("p",null,"Rules in this rule set report issues related to how code throws and handles Exceptions."),(0,i.kt)("h3",{id:"exceptionraisedinunexpectedlocation"},"ExceptionRaisedInUnexpectedLocation"),(0,i.kt)("p",null,"This rule reports functions which should never throw an exception. If a function exists that does throw\nan exception it will be reported. By default, this rule checks ",(0,i.kt)("inlineCode",{parentName:"p"},"toString"),", ",(0,i.kt)("inlineCode",{parentName:"p"},"hashCode"),", ",(0,i.kt)("inlineCode",{parentName:"p"},"equals")," and\n",(0,i.kt)("inlineCode",{parentName:"p"},"finalize"),". This rule is configurable via the ",(0,i.kt)("inlineCode",{parentName:"p"},"methodNames")," configuration to change the list of functions which\nshould not throw any exceptions."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"configuration-options"},"Configuration options:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"methodNames")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"['equals', 'finalize', 'hashCode', 'toString']"),")"),(0,i.kt)("p",{parentName:"li"},"methods which should not throw exceptions"))),(0,i.kt)("h4",{id:"noncompliant-code"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"class Foo {\n\n    override fun toString(): String {\n        throw IllegalStateException() // exception should not be thrown here\n    }\n}\n")),(0,i.kt)("h3",{id:"instanceofcheckforexception"},"InstanceOfCheckForException"),(0,i.kt)("p",null,"This rule reports ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," blocks which check for the type of exception via ",(0,i.kt)("inlineCode",{parentName:"p"},"is")," checks or casts.\nInstead of catching generic exception types and then checking for specific exception types the code should\nuse multiple catch blocks. These catch blocks should then catch the specific exceptions."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": No"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"noncompliant-code-1"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ... do some I/O\n    } catch(e: IOException) {\n        if (e is MyException || (e as MyException) != null) { }\n    }\n}\n")),(0,i.kt)("h4",{id:"compliant-code"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ... do some I/O\n    } catch(e: MyException) {\n    } catch(e: IOException) {\n    }\n}\n")),(0,i.kt)("h3",{id:"notimplementeddeclaration"},"NotImplementedDeclaration"),(0,i.kt)("p",null,"This rule reports all exceptions of the type ",(0,i.kt)("inlineCode",{parentName:"p"},"NotImplementedError")," that are thrown. It also reports all ",(0,i.kt)("inlineCode",{parentName:"p"},"TODO(..)"),"\nfunctions.\nThese indicate that functionality is still under development and will not work properly. Both of these should only\nserve as temporary declarations and should not be put into production environments."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": No"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"noncompliant-code-2"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},'fun foo() {\n    throw NotImplementedError()\n}\n\nfun todo() {\n    TODO("")\n}\n')),(0,i.kt)("h3",{id:"objectextendsthrowable"},"ObjectExtendsThrowable"),(0,i.kt)("p",null,"This rule reports all ",(0,i.kt)("inlineCode",{parentName:"p"},"objects")," including ",(0,i.kt)("inlineCode",{parentName:"p"},"companion objects")," that extend any type of\n",(0,i.kt)("inlineCode",{parentName:"p"},"Throwable"),". Throwable instances are not intended for reuse as they are stateful and contain\nmutable information about a specific exception or error. Hence, global singleton ",(0,i.kt)("inlineCode",{parentName:"p"},"Throwables"),"\nshould be avoided."),(0,i.kt)("p",null,"See ",(0,i.kt)("a",{parentName:"p",href:"https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview"},"https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview"),"\nSee ",(0,i.kt)("a",{parentName:"p",href:"https://kotlinlang.org/docs/object-declarations.html#companion-objects"},"https://kotlinlang.org/docs/object-declarations.html#companion-objects")),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": No"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Requires Type Resolution")),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 10min"),(0,i.kt)("h4",{id:"noncompliant-code-3"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"object InvalidCredentialsException : Throwable()\n\nobject BanException : Exception()\n\nobject AuthException : RuntimeException()\n")),(0,i.kt)("h4",{id:"compliant-code-1"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"class InvalidCredentialsException : Throwable()\n\nclass BanException : Exception()\n\nclass AuthException : RuntimeException()\n")),(0,i.kt)("h3",{id:"printstacktrace"},"PrintStackTrace"),(0,i.kt)("p",null,"This rule reports code that tries to print the stacktrace of an exception. Instead of simply printing a stacktrace\na better logging solution should be used."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"noncompliant-code-4"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    Thread.dumpStack()\n}\n\nfun bar() {\n    try {\n        // ...\n    } catch (e: IOException) {\n        e.printStackTrace()\n    }\n}\n")),(0,i.kt)("h4",{id:"compliant-code-2"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"val LOGGER = Logger.getLogger()\n\nfun bar() {\n    try {\n        // ...\n    } catch (e: IOException) {\n        LOGGER.info(e)\n    }\n}\n")),(0,i.kt)("h3",{id:"rethrowcaughtexception"},"RethrowCaughtException"),(0,i.kt)("p",null,"This rule reports all exceptions that are caught and then later re-thrown without modification.\nIt ignores cases:"),(0,i.kt)("ol",null,(0,i.kt)("li",{parentName:"ol"},"When caught exceptions that are rethrown if there is work done before that."),(0,i.kt)("li",{parentName:"ol"},"When there are more than one catch in try block and at least one of them has some work.")),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 5min"),(0,i.kt)("h4",{id:"noncompliant-code-5"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ...\n    } catch (e: IOException) {\n        throw e\n    }\n}\n")),(0,i.kt)("h4",{id:"compliant-code-3"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ...\n    } catch (e: IOException) {\n        throw MyException(e)\n    }\n    try {\n        // ...\n    } catch (e: IOException) {\n        print(e)\n        throw e\n    }\n    try {\n        // ...\n    } catch (e: IOException) {\n        print(e.message)\n        throw e\n    }\n\n    try {\n        // ...\n    } catch (e: IOException) {\n        throw e\n    } catch (e: Exception) {\n        print(e.message)\n    }\n}\n")),(0,i.kt)("h3",{id:"returnfromfinally"},"ReturnFromFinally"),(0,i.kt)("p",null,"Reports all ",(0,i.kt)("inlineCode",{parentName:"p"},"return")," statements in ",(0,i.kt)("inlineCode",{parentName:"p"},"finally")," blocks.\nUsing ",(0,i.kt)("inlineCode",{parentName:"p"},"return")," statements in ",(0,i.kt)("inlineCode",{parentName:"p"},"finally")," blocks can discard and hide exceptions that are thrown in the ",(0,i.kt)("inlineCode",{parentName:"p"},"try")," block.\nFurthermore, this rule reports values from ",(0,i.kt)("inlineCode",{parentName:"p"},"finally")," blocks, if the corresponding ",(0,i.kt)("inlineCode",{parentName:"p"},"try")," is used as an expression."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Requires Type Resolution")),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"configuration-options-1"},"Configuration options:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"ignoreLabeled")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"false"),")"),(0,i.kt)("p",{parentName:"li"},"ignores labeled return statements"))),(0,i.kt)("h4",{id:"noncompliant-code-6"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},'fun foo() {\n    try {\n        throw MyException()\n    } finally {\n        return // prevents MyException from being propagated\n    }\n}\n\nval a: String = try { "s" } catch (e: Exception) { "e" } finally { "f" }\n')),(0,i.kt)("h3",{id:"swallowedexception"},"SwallowedException"),(0,i.kt)("p",null,"Exceptions should not be swallowed. This rule reports all instances where exceptions are ",(0,i.kt)("inlineCode",{parentName:"p"},"caught")," and not correctly\npassed (e.g. as a cause) into a newly thrown exception."),(0,i.kt)("p",null,"The exception types configured in ",(0,i.kt)("inlineCode",{parentName:"p"},"ignoredExceptionTypes")," indicate nonexceptional outcomes.\nThese by default configured exception types are part of Java.\nTherefore, Kotlin developers have to handle them by using the catch clause.\nFor that reason, this rule ignores that these configured exception types are caught."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"configuration-options-2"},"Configuration options:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"ignoredExceptionTypes")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"['InterruptedException', 'MalformedURLException', 'NumberFormatException', 'ParseException']"),")"),(0,i.kt)("p",{parentName:"li"},"exception types which should be ignored (both in the catch clause and body)")),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"allowedExceptionNameRegex")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"'_|(ignore|expected).*'"),")"),(0,i.kt)("p",{parentName:"li"},"ignores too generic exception types which match this regex"))),(0,i.kt)("h4",{id:"noncompliant-code-7"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ...\n    } catch(e: IOException) {\n        throw MyException(e.message) // e is swallowed\n    }\n    try {\n        // ...\n    } catch(e: IOException) {\n        throw MyException() // e is swallowed\n    }\n    try {\n        // ...\n    } catch(e: IOException) {\n        bar() // exception is unused\n    }\n}\n")),(0,i.kt)("h4",{id:"compliant-code-4"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ...\n    } catch(e: IOException) {\n        throw MyException(e)\n    }\n    try {\n        // ...\n    } catch(e: IOException) {\n        println(e) // logging is ok here\n    }\n}\n")),(0,i.kt)("h3",{id:"throwingexceptionfromfinally"},"ThrowingExceptionFromFinally"),(0,i.kt)("p",null,"This rule reports all cases where exceptions are thrown from a ",(0,i.kt)("inlineCode",{parentName:"p"},"finally")," block. Throwing exceptions from a ",(0,i.kt)("inlineCode",{parentName:"p"},"finally"),"\nblock should be avoided as it can lead to confusion and discarded exceptions."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"noncompliant-code-8"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ...\n    } finally {\n        throw IOException()\n    }\n}\n")),(0,i.kt)("h3",{id:"throwingexceptioninmain"},"ThrowingExceptionInMain"),(0,i.kt)("p",null,"This rule reports all exceptions that are thrown in a ",(0,i.kt)("inlineCode",{parentName:"p"},"main"),' method.\nAn exception should only be thrown if it can be handled by a "higher" function.'),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": No"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"noncompliant-code-9"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun main(args: Array<String>) {\n    // ...\n    throw IOException() // exception should not be thrown here\n}\n")),(0,i.kt)("h3",{id:"throwingexceptionswithoutmessageorcause"},"ThrowingExceptionsWithoutMessageOrCause"),(0,i.kt)("p",null,"This rule reports all exceptions which are thrown without arguments or further description.\nExceptions should always call one of the constructor overloads to provide a message or a cause.\nExceptions should be meaningful and contain as much detail about the error case as possible. This will help to track\ndown an underlying issue in a better way."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 5min"),(0,i.kt)("h4",{id:"configuration-options-3"},"Configuration options:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"exceptions")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"['ArrayIndexOutOfBoundsException', 'Exception', 'IllegalArgumentException', 'IllegalMonitorStateException', 'IllegalStateException', 'IndexOutOfBoundsException', 'NullPointerException', 'RuntimeException', 'Throwable']"),")"),(0,i.kt)("p",{parentName:"li"},"exceptions which should not be thrown without message or cause"))),(0,i.kt)("h4",{id:"noncompliant-code-10"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo(bar: Int) {\n    if (bar < 1) {\n        throw IllegalArgumentException()\n    }\n    // ...\n}\n")),(0,i.kt)("h4",{id:"compliant-code-5"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},'fun foo(bar: Int) {\n    if (bar < 1) {\n        throw IllegalArgumentException("bar must be greater than zero")\n    }\n    // ...\n}\n')),(0,i.kt)("h3",{id:"throwingnewinstanceofsameexception"},"ThrowingNewInstanceOfSameException"),(0,i.kt)("p",null,"Exceptions should not be wrapped inside the same exception type and then rethrown. Prefer wrapping exceptions in more\nmeaningful exception types."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.16.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 5min"),(0,i.kt)("h4",{id:"noncompliant-code-11"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ...\n    } catch (e: IllegalStateException) {\n        throw IllegalStateException(e) // rethrows the same exception\n    }\n}\n")),(0,i.kt)("h4",{id:"compliant-code-6"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ...\n    } catch (e: IllegalStateException) {\n        throw MyException(e)\n    }\n}\n")),(0,i.kt)("h3",{id:"toogenericexceptioncaught"},"TooGenericExceptionCaught"),(0,i.kt)("p",null,"This rule reports ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," blocks for exceptions that have a type that is too generic.\nIt should be preferred to catch specific exceptions to the case that is currently handled. If the scope of the caught\nexception is too broad it can lead to unintended exceptions being caught."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.0.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"configuration-options-4"},"Configuration options:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"exceptionNames")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"['ArrayIndexOutOfBoundsException', 'Error', 'Exception', 'IllegalMonitorStateException', 'IndexOutOfBoundsException', 'NullPointerException', 'RuntimeException', 'Throwable']"),")"),(0,i.kt)("p",{parentName:"li"},"exceptions which are too generic and should not be caught")),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"allowedExceptionNameRegex")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"'_|(ignore|expected).*'"),")"),(0,i.kt)("p",{parentName:"li"},"ignores too generic exception types which match this regex"))),(0,i.kt)("h4",{id:"noncompliant-code-12"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ... do some I/O\n    } catch(e: Exception) { } // too generic exception caught here\n}\n")),(0,i.kt)("h4",{id:"compliant-code-7"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo() {\n    try {\n        // ... do some I/O\n    } catch(e: IOException) { }\n}\n")),(0,i.kt)("h3",{id:"toogenericexceptionthrown"},"TooGenericExceptionThrown"),(0,i.kt)("p",null,"This rule reports thrown exceptions that have a type that is too generic. It should be preferred to throw specific\nexceptions to the case that has currently occurred."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Active by default"),": Yes - Since v1.0.0"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Debt"),": 20min"),(0,i.kt)("h4",{id:"configuration-options-5"},"Configuration options:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"exceptionNames")," (default: ",(0,i.kt)("inlineCode",{parentName:"p"},"['Error', 'Exception', 'RuntimeException', 'Throwable']"),")"),(0,i.kt)("p",{parentName:"li"},"exceptions which are too generic and should not be thrown"))),(0,i.kt)("h4",{id:"noncompliant-code-13"},"Noncompliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},"fun foo(bar: Int) {\n    if (bar < 1) {\n        throw Exception() // too generic exception thrown here\n    }\n    // ...\n}\n")),(0,i.kt)("h4",{id:"compliant-code-8"},"Compliant Code:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-kotlin"},'fun foo(bar: Int) {\n    if (bar < 1) {\n        throw IllegalArgumentException("bar must be greater than zero")\n    }\n    // ...\n}\n')))}m.isMDXComponent=!0}}]);